# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41beb5eef5d76b1b09781103ac44d98171221c7c3cf47e49509aaae84b47fb0c86577740596eda43ae4e1416ec4219b36d83befa4d4053b110428df0fc3ccce

test:
  secret_key_base: 0f6eaf5d147cbc90c72b05b10e09e2b59ea7a4668fb3bac5fd7f06853c77abaf6dd15c2f48e794f20a246acb72e3be4ddce18ab36086e67eeb8afaa14eda91d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
